### ISSUE TITLE
Bug: Not seeing the option to login

### ISSUE THREAD

**Issue by mudit94** [akionet/frontend-qa-exam#2]
Hi Team,

I am unable to find the option to login to the application . 

@akionet can you please look into the application ?
![image](https://github.com/akionet/frontend-qa-exam/assets/10437606/90f0feed-8007-44cd-86ed-edc60882cbb8)

**Comment by mudit94** [comment]
Hi @akionet , please ignore this

**Comment by akionet** [comment]
Hi, Login is not required for this exam. Make the assumption that the user is already logged in and security is disabled in the test env you're using aka your localhost.
